/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop_project;
import java.util.ArrayList;


/**
 *
 * @author ADMIN
 */
public class Issue extends javax.swing.JFrame {
    int s;
    private String str;

    /**
     * Creates new form Issue
     */
    static ArrayList<Book> books = new ArrayList<Book>();
    
    public Issue(String s){
        str = s;
    }
    User_Type w = new User_Type();
     String UserId = w.getUserId();
     Book_finished k = new Book_finished();
    
    public Issue() {
        initComponents();
        books.add(new Book("Meta-Physics"));
        books.add(new Book("Calculus- for beginners"));
        books.add(new Book("Introduction to statistics"));
        books.add(new Book("Discrete Math Fundementals"));
        books.add(new Book("Object Oriented Programming Fundamentals"));
        books.add(new Book("Advanced Calculus"));
        books.add(new Book("Accounts and Finance"));
        books.add(new Book("Religion- A perspective from Philisophers"));
        books.add(new Book("Sociology and Humanity"));
        books.add(new Book("A Race against time"));
        books.add(new Book("Digital Logic Design"));
        books.add(new Book("Artificial Intelligence- A doom for humanity?"));
        books.add(new Book("Data Science for advanced Machine Learning"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        C2 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        C8 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        C11 = new javax.swing.JButton();
        C12 = new javax.swing.JButton();
        C13 = new javax.swing.JButton();
        C9 = new javax.swing.JButton();
        C10 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jCheckBox5.setText("jCheckBox5");

        jLabel1.setText("jLabel1");

        jRadioButton1.setText("jRadioButton1");

        jButton1.setText("ISSUE");

        jButton4.setText("ISSUE");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        C1.setBackground(new java.awt.Color(185, 223, 140));
        C1.setForeground(new java.awt.Color(117, 5, 168));
        C1.setText("ISSUE");
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(1);
        jTextArea1.setText("Meta-Physics\n\nCalculus- for beginners\n\nIntroduction to statistics\n\nDiscrete Math Fundementals\n\nObject Oriented Programming Fundamentals\n\nAdvanced Calculus\n\nAccounts and Finance\n\nReligion- A perspective from Philisophers\n\nSociology and Humanity\n\nA Race against time\n\nDigital Logic Design\n\nArtificial Intelligence- A doom for humanity?\n\nData Science for advanced Machine Learning");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAlignmentX(1.0F);
        jTextArea1.setAlignmentY(1.5F);
        jScrollPane1.setViewportView(jTextArea1);

        C2.setBackground(new java.awt.Color(185, 223, 140));
        C2.setForeground(new java.awt.Color(117, 5, 168));
        C2.setText("ISSUE");
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });

        C3.setBackground(new java.awt.Color(185, 223, 140));
        C3.setForeground(new java.awt.Color(117, 5, 168));
        C3.setText("ISSUE");
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });

        C4.setBackground(new java.awt.Color(185, 223, 140));
        C4.setForeground(new java.awt.Color(117, 5, 168));
        C4.setText("ISSUE");
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });

        C7.setBackground(new java.awt.Color(185, 223, 140));
        C7.setForeground(new java.awt.Color(117, 5, 168));
        C7.setText("ISSUE");
        C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C7ActionPerformed(evt);
            }
        });

        C8.setBackground(new java.awt.Color(185, 223, 140));
        C8.setForeground(new java.awt.Color(117, 5, 168));
        C8.setText("ISSUE");
        C8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C8ActionPerformed(evt);
            }
        });

        C5.setBackground(new java.awt.Color(185, 223, 140));
        C5.setForeground(new java.awt.Color(117, 5, 168));
        C5.setText("ISSUE");
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });

        C6.setBackground(new java.awt.Color(185, 223, 140));
        C6.setForeground(new java.awt.Color(117, 5, 168));
        C6.setText("ISSUE");
        C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6ActionPerformed(evt);
            }
        });

        C11.setBackground(new java.awt.Color(185, 223, 140));
        C11.setForeground(new java.awt.Color(117, 5, 168));
        C11.setText("ISSUE");
        C11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C11ActionPerformed(evt);
            }
        });

        C12.setBackground(new java.awt.Color(185, 223, 140));
        C12.setForeground(new java.awt.Color(117, 5, 168));
        C12.setText("ISSUE");
        C12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C12ActionPerformed(evt);
            }
        });

        C13.setBackground(new java.awt.Color(185, 223, 140));
        C13.setForeground(new java.awt.Color(117, 5, 168));
        C13.setText("ISSUE");
        C13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C13ActionPerformed(evt);
            }
        });

        C9.setBackground(new java.awt.Color(185, 223, 140));
        C9.setForeground(new java.awt.Color(117, 5, 168));
        C9.setText("ISSUE");
        C9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C9ActionPerformed(evt);
            }
        });

        C10.setBackground(new java.awt.Color(185, 223, 140));
        C10.setForeground(new java.awt.Color(117, 5, 168));
        C10.setText("ISSUE");
        C10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C10ActionPerformed(evt);
            }
        });

        jButton3.setText("< Return");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {C1, C10, C11, C12, C13, C2, C3, C4, C5, C6, C7, C8, C9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(C2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(C3)
                        .addGap(11, 11, 11)
                        .addComponent(C4)
                        .addGap(18, 18, 18)
                        .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(C6)
                        .addGap(18, 18, 18)
                        .addComponent(C7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(C8)
                        .addGap(18, 18, 18)
                        .addComponent(C9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(C10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(C11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(C12)
                        .addGap(18, 18, 18)
                        .addComponent(C13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {C1, C10, C11, C12, C13, C2, C3, C4, C5, C6, C7, C8, C9});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<books.size(); i++){
            if(books.get(i).getName().equals("Meta-Physics")){
                books.get(i).setQty();
                  if (books.get(i).getQty()>=0) {
                      System.out.println("User "+UserId + " have issued " + books.get(i).getName());
                      System.out.println(books.get(i).getName()+" left are " +books.get(i).getQty() + ".");
                      System.out.println(" ");
                  }
                else k.show();
            }
        }
    }//GEN-LAST:event_C1ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<books.size(); i++){
            books.get(i).setQty();
            if(books.get(i).getName().equals("Calculus- for beginners")){
                    if (books.get(i).getQty()>=0) {
                      System.out.println("User "+UserId + " have issued " + books.get(i).getName());
                      System.out.println(books.get(i).getName()+" left are " +books.get(i).getQty() + ".");
                      System.out.println(" ");
                  }
                else k.show();            }
        }
    }//GEN-LAST:event_C2ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<books.size(); i++){
            if(books.get(i).getName().equals("Introduction to statistics")){
                books.get(i).setQty();
            if (books.get(i).getQty()>=0) {
                      System.out.println("User "+UserId + " have issued " + books.get(i).getName());
                      System.out.println(books.get(i).getName()+" left are " +books.get(i).getQty() + ".");
                      System.out.println(" ");
                  }
                else k.show();            }
        }
    }//GEN-LAST:event_C3ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<books.size(); i++){
            if(books.get(i).getName().equals("Discrete Math Fundementals")){
                books.get(i).setQty();
                    if (books.get(i).getQty()>=0) {
                      System.out.println("User "+UserId + " have issued " + books.get(i).getName());
                      System.out.println(books.get(i).getName()+" left are " +books.get(i).getQty() + ".");
                      System.out.println(" ");
                  }
                else k.show();            
            }
        }
    }//GEN-LAST:event_C4ActionPerformed

    private void C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C7ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<books.size(); i++){
            if(books.get(i).getName().equals("Accounts and Finance")){
                books.get(i).setQty();
if (books.get(i).getQty()>=0) {
                      System.out.println("User "+UserId + " have issued " + books.get(i).getName());
                      System.out.println(books.get(i).getName()+" left are " +books.get(i).getQty() + ".");
                      System.out.println(" ");
                  }
                else k.show();            }
        }
    }//GEN-LAST:event_C7ActionPerformed

    private void C8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C8ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<books.size(); i++){
            if(books.get(i).getName().equals("Religion- A perspective from Philisophers")){
                books.get(i).setQty();
if (books.get(i).getQty()>=0) {
                      System.out.println("User "+UserId + " have issued " + books.get(i).getName());
                      System.out.println(books.get(i).getName()+" left are " +books.get(i).getQty() + ".");
                      System.out.println(" ");
                  }
                else k.show();            }
        }
    }//GEN-LAST:event_C8ActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<books.size(); i++){
            if(books.get(i).getName().equals("Object Oriented Programming Fundamentals")){
                books.get(i).setQty();
if (books.get(i).getQty()>=0) {
                      System.out.println("User "+UserId + " have issued " + books.get(i).getName());
                      System.out.println(books.get(i).getName()+" left are " +books.get(i).getQty() + ".");
                      System.out.println(" ");
                  }
                else k.show();        }
        }
    }//GEN-LAST:event_C5ActionPerformed

    private void C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<books.size(); i++){
            if(books.get(i).getName().equals("Advanced Calculus")){
                books.get(i).setQty();
if (books.get(i).getQty()>=0) {
                      System.out.println("User "+UserId + " have issued " + books.get(i).getName());
                      System.out.println(books.get(i).getName()+" left are " +books.get(i).getQty() + ".");
                      System.out.println(" ");
                  }
                else k.show();            }
        }
    }//GEN-LAST:event_C6ActionPerformed

    private void C11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C11ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<books.size(); i++){
            if(books.get(i).getName().equals("Digital Logic Design")){
                books.get(i).setQty();
if (books.get(i).getQty()>=0) {
                      System.out.println("User "+UserId + " have issued " + books.get(i).getName());
                      System.out.println(books.get(i).getName()+" left are " +books.get(i).getQty() + ".");
                      System.out.println(" ");
                  }
                else k.show();            }
        }
    }//GEN-LAST:event_C11ActionPerformed

    private void C12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C12ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<books.size(); i++){
            if(books.get(i).getName().equals("Artificial Intelligence- A doom for humanity?")){
                books.get(i).setQty();
if (books.get(i).getQty()>=0) {
                      System.out.println("User "+UserId + " have issued " + books.get(i).getName());
                      System.out.println(books.get(i).getName()+" left are " +books.get(i).getQty() + ".");
                      System.out.println(" ");
                  }
                else k.show();            }
        }
    }//GEN-LAST:event_C12ActionPerformed

    private void C13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C13ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<books.size(); i++){
            if(books.get(i).getName().equals("Data Science for advanced Machine Learning")){
                books.get(i).setQty();
if (books.get(i).getQty()>=0) {
                      System.out.println("User "+UserId + " have issued " + books.get(i).getName());
                      System.out.println(books.get(i).getName()+" left are " +books.get(i).getQty() + ".");
                      System.out.println(" ");
                  }
                else k.show();            }
        }
    }//GEN-LAST:event_C13ActionPerformed

    private void C9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C9ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<books.size(); i++){
            if(books.get(i).getName().equals("Sociology and Humanity")){
                books.get(i).setQty();
if (books.get(i).getQty()>=0) {
                      System.out.println("User "+UserId + " have issued " + books.get(i).getName());
                      System.out.println(books.get(i).getName()+" left are " +books.get(i).getQty() + ".");
                      System.out.println(" ");
                  }
                else k.show();            }
        }
    }//GEN-LAST:event_C9ActionPerformed

    private void C10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C10ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<books.size(); i++){
            if(books.get(i).getName().equals("A Race against time")){
                books.get(i).setQty();
if (books.get(i).getQty()>=0) {
                      System.out.println("User "+UserId + " have issued " + books.get(i).getName());
                      System.out.println(books.get(i).getName()+" left are " +books.get(i).getQty() + ".");
                      System.out.println(" ");
                  }
                else k.show();            }
        }
    }//GEN-LAST:event_C10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.hide();
        /*Student x = new Student();
        Teacher y = new Teacher();
        Faculty z = new Faculty();
        Graduate a = new Graduate();
        if(str == "Student"){
            x.show();
            this.hide();
        }
        
        if(str == "Teacher"){
            y.show();
            this.hide();
        }
        
        if(str == "Faculty"){
            z.show();
            this.hide();
        }
        
        if(str == "Graduate"){
            a.show();
            this.hide();
        }*/
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Issue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C1;
    private javax.swing.JButton C10;
    private javax.swing.JButton C11;
    private javax.swing.JButton C12;
    private javax.swing.JButton C13;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JButton C8;
    private javax.swing.JButton C9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
